# Generated by Django 5.2.2 on 2025-06-12 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
