# Generated by Django 5.2.2 on 2025-06-09 11:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_favorite_products'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favorite_products',
            new_name='FavouriteProducts',
        ),
        migrations.AlterModelOptions(
            name='favouriteproducts',
            options={'verbose_name': 'Favourite Products', 'verbose_name_plural': 'Favourite Products'},
        ),
    ]
