# Generated by Django 5.2.2 on 2025-06-26 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
